version: "3"

services:
  generator:
    build:
      context: ./generator
      dockerfile: Dockerfile
    depends_on:
      - kafkac
    environment:
      - KAFKA_BROKER=kafkac:9092
      - KAFKA_TOPIC=transactions
      - SEED=0
      - CARD_COUNT=10
      - CARD_OWNERS_COUNT=1
      - WAIT_TIME_MS=5000
    restart: on-failure
    networks:
      - kafka-network

  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - "9000:9000"
    environment:
      - KAFKA_BROKERCONNECT=kafkac:9092
      - JVM_OPTS=-Xms32M -Xmx64M
      - SERVER_SERVLET_CONTEXTPATH=/
    depends_on:
      - kafkac
    networks:
      - kafka-network

  alerts-reader:
    build:
      context: ./alerts-notification-api-py
      dockerfile: Dockerfile
    ports:
      - "12000:12000"
    depends_on:
      - kafkac
    networks:
      - kafka-network

  # alerts-notification-api:
  #   build:
  #     context: ./alerts-notification-api
  #     dockerfile: Dockerfile
  #   ports:
  #     - "4000:12000"
  #   depends_on:
  #     - kafkac
  #   restart: on-failure
  #   networks:
  #     - kafka-network
    
  kafkac:
    image: "bitnami/kafka:latest"
    ports:
      - '9092:9092'
    environment:
      # not recommended for production
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafkac:9092
      # - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - BITNAMI_DEBUG=yes
    networks:
      - kafka-network

  # https://nightlies.apache.org/flink/flink-docs-master/docs/deployment/resource-providers/standalone/docker/#flink-with-docker-compose
  jobmanager:
    build:
      context: ./frauddetection
      dockerfile: Dockerfile
    depends_on:
      - generator
    command: standalone-job --job-classname spendreport.FraudDetectionJob
    ports:
      - "8081:8081"
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        parallelism.default: 2
    restart: on-failure  
    networks:
     - kafka-network      

  taskmanager:
    build:
      context: ./frauddetection
      dockerfile: Dockerfile
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2 
        parallelism.default: 2
    networks:
      - kafka-network

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

networks:
  kafka-network:
    driver: bridge