version: "3"

services:
  generator:
    build:
      context: ./generator
      dockerfile: Dockerfile
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKERS=localhost:9092
      - KAFKA_TOPIC=test
      - SEED=0
      - CARD_COUNT=10
      - CARD_OWNERS_COUNT=1
      - WAIT_TIME_MS=5000
    restart: on-failure
    networks:
      - kafka-network

  kafka:
    image: "bitnami/kafka:latest"
    ports:
      - '9092:9092'
    environment:
      # not recommended for production
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - BITNAMI_DEBUG=yes
    networks:
      - kafka-network

  # https://nightlies.apache.org/flink/flink-docs-master/docs/deployment/resource-providers/standalone/docker/#flink-with-docker-compose
  jobmanager:
    build:
      context: ./frauddetection
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager        

  taskmanager:
    image: flink:1.17-java11
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2 

networks:
  kafka-network:
    driver: bridge